#ifndef ESCCOIN_CHAINPARAMSSEEDS_H
#define ESCCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the elspero network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
	{{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xA7,0x47,0x6D,0xA6}, 31500}
};

static SeedSpec6 pnSeed6_test[] = {
	
};

static SeedSpec6 pnSeed6_dev[] = {

};
#endif // ESCCOIN_CHAINPARAMSSEEDS_H
